# Supported intents (upper snake for API consistency)
INTENT_LEAVE_BALANCE = "LEAVE_BALANCE"
INTENT_LEAVE_REQUEST = "LEAVE_REQUEST"
INTENT_WFH_REQUEST = "WFH_REQUEST"
INTENT_EXPENSE_CLAIM = "EXPENSE_CLAIM"
INTENT_EXPENSE_STATUS = "EXPENSE_STATUS"
INTENT_ATTENDANCE_CORRECTION = "ATTENDANCE_CORRECTION"
INTENT_REQUEST_STATUS = "REQUEST_STATUS"
INTENT_HR_POLICY = "HR_POLICY"
INTENT_APPROVAL_ESCALATION = "APPROVAL_ESCALATION"
INTENT_UNKNOWN = "UNKNOWN"

ALL_INTENTS = frozenset(
    {
        INTENT_LEAVE_BALANCE,
        INTENT_LEAVE_REQUEST,
        INTENT_WFH_REQUEST,
        INTENT_EXPENSE_CLAIM,
        INTENT_EXPENSE_STATUS,
        INTENT_ATTENDANCE_CORRECTION,
        INTENT_REQUEST_STATUS,
        INTENT_HR_POLICY,
        INTENT_APPROVAL_ESCALATION,
        INTENT_UNKNOWN,
    }
)
